### ISSUE TITLE
Implementation: Move AWS ECS Services to NAT 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/Operations#4]
Follow up of: https://github.com/OA-PASS/Operations/issues/1 

toward solving this ticket https://github.com/OA-PASS/general-issues/issues/93
Please specify the time you plan on doing this and whether any testing would take place afterward. 

Thanks.

**Comment by derekbelrose** [comment]
~~I plan on doing Demo first.  I would hope that someone would be able to poke at it for a bit to make sure it is working as expected.~~

~~For each environment (Demo, Production) the process is as follow:~~
~~set nat_network to true~~
~~run terraform plan and verify output~~
~~run terraform apply, this takes about 30 seconds~~
~~This will create new tasks and let the old ones properly shut down.~~

~~I estimate each environment should take about 10 minutes to start things up and shut the old ones down.  Once done, it can be verified by testers.~~

~~I don't have a date/time yet.  I would think I could do this to demo on Monday assuming there are no demos taking place.  If that passes tests, I could do production at any point after that.~~

**Comment by derekbelrose** [comment]
After discussing with @htpvu, implementation is estimated to be less than a day's work.  In this case, nearly all of the implementation was done in the investigative phase.

We can move forward with Deployment/Test phase as early Monday if that's ok with stakeholders.

I would like to do Demo first, to minimize risk.  While there is no risk of data corruption, the downtime can be minimalized by doing Demo first and having devs quickly test to ensure expected behavior.

**Comment by htpvu** [comment]
This has been done in demo. Next step is to move is to Production with this configuration.
